        	<div class="leftside">
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla libero turpis, condimentum vel euismod quis, pellentesque pellentesque ante. Aenean ut dui vel arcu euismod pretium cursus tempor orci. Aliquam urna ante, pulvinar nec dictum quis, vehicula eu ante. Donec iaculis vestibulum ornare. Morbi rhoncus lectus luctus massa congue facilisis. Curabitur hendrerit porttitor pharetra. Phasellus non nunc dolor. Maecenas sagittis pellentesque urna, in tempus nibh vestibulum eleifend. Quisque ac ligula arcu. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras pulvinar, est ac scelerisque mattis, nisi tellus laoreet nisl, sed volutpat sapien orci in dolor. Praesent nulla sem, vulputate vel accumsan a, fermentum vitae leo. Sed quam massa, eleifend ut porttitor quis, tincidunt a turpis. Ut dignissim pharetra magna, ac vehicula purus auctor vel. Sed vel urna in metus malesuada cursus.<br /><br />

Nulla vitae faucibus ipsum. Pellentesque libero mi, imperdiet vel placerat id, lobortis in purus. Nullam et mollis mi. Duis nec erat pharetra ante blandit tincidunt. Maecenas ac mi bibendum dui eleifend iaculis sed non velit. Curabitur et posuere metus. Sed bibendum, lectus eu congue vestibulum, nisi ante condimentum eros, adipiscing malesuada nulla justo a quam. Quisque at mi a neque varius lacinia sit amet eu arcu. Etiam venenatis posuere neque. Pellentesque sagittis tincidunt urna, a consequat felis rhoncus sed. Mauris velit turpis, pellentesque vitae aliquam a, rutrum ut sem. Nam vel justo eu turpis fermentum euismod. Sed luctus felis interdum justo laoreet gravida. Mauris eget rutrum leo. In in nunc ut sem facilisis tristique. Suspendisse potenti. Morbi venenatis vestibulum placerat. Aenean vitae lacus vitae lorem pretium pretium.<br /><br />

Cras scelerisque tincidunt sem, nec interdum ante venenatis semper. Cras in dolor felis. Fusce porta sapien augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Etiam cursus risus nec urna venenatis venenatis. Morbi dignissim pulvinar odio, congue tristique dolor posuere non. Integer condimentum diam id tortor interdum eu mollis neque aliquam. Curabitur nulla tortor, vestibulum sed mattis sit amet, cursus in tellus. Donec et nisi eget lectus ultrices scelerisque. Donec suscipit lacus nisi, quis imperdiet libero. Etiam justo est, venenatis et molestie ultrices, mollis vitae tellus. Suspendisse potenti. Sed fermentum tortor ac ligula vulputate vel placerat libero varius. Sed quis orci dolor, at tristique felis. Nullam in turpis libero, et interdum justo. Aenean sed aliquam turpis. Etiam non aliquet lectus. In condimentum sodales ante, ultricies hendrerit enim egestas pulvinar. Sed consectetur malesuada consectetur. Praesent cursus blandit augue et interdum.<br /><br />

Suspendisse blandit, nibh id vulputate vulputate, ipsum nunc sollicitudin ante, id lobortis est sapien quis nunc. Sed sed orci tellus. Phasellus enim diam, tincidunt sed viverra eu, mollis eget lacus. Nulla dignissim mollis urna nec hendrerit. Aliquam accumsan eleifend erat, consequat vestibulum arcu ullamcorper eu. Sed non mi leo. Donec ornare, lectus ac pellentesque accumsan, lectus dolor semper tellus, ac elementum erat lorem nec tortor. Aenean quis metus sed purus gravida varius nec id enim. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Vestibulum erat sapien, fringilla ac fringilla quis, bibendum eu quam. Sed non lorem quis arcu interdum fermentum non ut velit. Sed dignissim, sem rutrum cursus bibendum, nisl nisl tincidunt velit, congue mattis mi ante sed lectus. Integer eget mauris nulla.<br /><br />

Nam a mauris vitae lectus pretium volutpat non non nisl. Proin auctor, quam et dignissim mollis, sapien arcu hendrerit libero, sit amet congue purus arcu id ligula. Donec ullamcorper urna ac enim suscipit faucibus. Quisque facilisis porttitor risus et aliquet. Duis commodo ultrices pulvinar. Vivamus vulputate interdum pretium. Proin a velit nisl, sit amet vehicula libero. Nullam convallis, est nec elementum sollicitudin, purus justo accumsan risus, quis commodo ligula orci eget nisi. Praesent condimentum cursus ligula ut lobortis. Sed quam tellus, adipiscing vel dapibus eget, tempus sit amet erat. Vestibulum nibh sapien, viverra a venenatis a, ullamcorper quis magna. Curabitur ut dignissim urna. Suspendisse odio augue, suscipit vel iaculis eu, eleifend vel massa. Nunc hendrerit, arcu id vehicula gravida, diam lacus tempus erat, quis porttitor lacus purus eu orci.
			</div>
            <div class="rightside">
                	<div class="r1"></div>
                    <div class="r2">
                    	<div class="item"><a href="#">Chủ đề 1</a></div>
                        <div class="item"><a href="#">Chủ đề 1</a></div>
                        <div class="item"><a href="#">Chủ đề 1</a></div>
                        <div class="item"><a href="#">Chủ đề 1</a></div>
                    </div>
                    <div class="r3"></div>
            </div>
